export const environment = {
  production: true,
  appName: "IDP-VPI",
  version: "1.0.0",
  backendUrl: "",
  authClientId: "30",
  authBaseUrl: "",
  forgotPasswordUrl: "",
  forgotPasswordConfirmationUrl: "http://localhost:4200/reset-password",
  reportUrl: "",
  reportServiceUrl: "",
  authUserTokenValidationUrl: "",
  authServiceTokenValidationUrl: "",
  redirectOnExitingApp: "login",
  redirectToHome: "home",
  pipUrl: "",
};
